[project]
name = "repoanalyze"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.3.0",
    "lightgbm>=4.7.0",
    "matplotlib>=3.11.1",
    "optuna>=4.9.0",
    "pandas>=2.3.2",
    "pandas-stubs~=3.0.5",
    "pygithub>=2.9.1",
    "python-dotenv>=1.2.3",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
]

[tool.basedpyright]
venvPath = "."
venv = ".venv"
pythonVersion = "3.11"
ignore = ["**/*.ipynb"]
